name: Free Buills Front Pipeline
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Bump version and push tag
      id: tagging
      uses: mathieudutour/github-tag-action@v4.5
      with:
        github_token: ${{ secrets.GIT_TOKEN }}

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tagging.outputs.new_tag }}
        name: Release ${{ steps.tagging.outputs.new_tag }}
        body: ${{ steps.tagging.outputs.changelog }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: warleyvods/freebills-fe:${{ steps.tagging.outputs.new_version }}
        platforms: linux/amd64,linux/arm64

    - name: Deploy Kubernetes
      uses: steebchen/kubectl@v2.1.1
      with:
        config: ${{ secrets.KUBE_CONFIG }}
        command: set image deployment/freebills-fe freebills-fe=warleyvods/freebills-fe:${{ steps.tagging.outputs.new_version }}

    - name: Discord
      uses: sarisia/actions-status-discord@v1.9.0
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "Front RH Web"
        description: "Build and Deploy to Server"
        username: GitHub Actions
